apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  template:
    spec:
      containers:
      - name: admin
        image: {{PG_FARM_SERVICE_IMAGE}}:{{BRANCH_TAG_NAME}}
        imagePullPolicy: Never
        command: ["npm", "run", "administration"]
        env:
        - name : "APP_URL"
          value : "http://localhost:3000"
        - name : "K8S_PLATFORM"
          value: "docker-desktop"
        volumeMounts:
        - name: src-administration
          mountPath: /services/administration
        - name: src-lib
          mountPath: /services/lib
        - name: src-models
          mountPath: /services/models
        - name: kubeconfig
          mountPath: /root/.kube
      volumes:
        - name: src-administration
          hostPath:
            path: {{REPO_DIR}}/services/administration
        - name: src-lib
          hostPath:
            path: {{REPO_DIR}}/services/lib
        - name: src-models
          hostPath:
            path: {{REPO_DIR}}/services/models
        - name: kubeconfig
          configMap:
            name: kubeconfig