apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        imagePullPolicy: Always
        command: ["npm", "run", "gateway"]
        env:
        - name: LOG_LEVEL
          value: "info"
        - name: PROXY_DEBUG
          value: "false"
        - name : "GOOGLE_APPLICATION_CREDENTIALS"
          value : "/etc/google/service-account.json"
        - name: SERVICE_NAME
          value: "gateway"
        envFrom:
        - secretRef:
            name: app-env
        resources:
          limits:
            memory: "2Gi"
            cpu: "2"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
          - mountPath: /etc/google
            name: service-account
      volumes:
      - name: service-account
        secret:
          secretName: service-account