apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: admin-db
spec:
  template: 
    spec:
      containers:
      - name: pg-helper
        image: localhost/local-dev/pgfarm-service:main
        volumeMounts:
        - name: gcs-fuse
          mountPath: /backups     
        - name: local-pghelpers
          mountPath: /services/pg-helper
      volumes:
      - name: gcs-fuse
        emptyDir: {}
      - name: local-pghelpers
        hostPath:
          path: /hosthome/Users/jrmerz/dev/library/pg-farm/services/pg-helper