apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: admin-db
spec:
  template: 
    spec:
      containers:
      - name: pg-helper
        image: {{PG_FARM_SERVICE_IMAGE}}:{{BRANCH_TAG_NAME}}
        volumeMounts:
        - name: gcs-fuse
          mountPath: /backups     
        - name: local-pghelpers
          mountPath: /services/pg-helper
      volumes:
      - name: gcs-fuse
        emptyDir: {}
      - name: local-pghelpers
        hostPath:
          path: /hosthome/{{REPO_DIR}}/services/pg-helper