apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  template:
    spec:
      containers:
      - name: gateway
        # command: ["/bin/bash", "-c", "tail -f /dev/null"]
        volumeMounts:
        - name: kubeconfig
          mountPath: /root/.kube
      volumes:
        - name: kubeconfig
          configMap:
            name: kubeconfig