apiVersion: v1
kind: Service
metadata:
  name: gateway-ingress
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 30543
  - name: http
    protocol: TCP
    port: 80
    nodePort: 30000
    targetPort: 80