apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        imagePullPolicy: Always
        command: ["npm", "run", "client"]
        env:
        - name: LOG_LEVEL
          value: "info"
        - name : "GOOGLE_APPLICATION_CREDENTIALS"
          value : "/etc/google/service-account.json"
        - name: SERVICE_NAME
          value: "client"
        envFrom:
        - secretRef:
            name: app-env
        resources:
          limits:
            memory: "2Gi"
            cpu: "2"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
          - mountPath: /etc/google
            name: service-account
      volumes:
      - name: service-account
        secret:
          secretName: service-account