apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: gateway
          image: us-docker.pkg.dev/pgfarm-419213/containers/pgfarm-service:0.5.9
          volumeMounts:
            - mountPath: /etc/pgfarm/certs/pgfarm.library.ucdavis.edu
              name: pgfarm-ssl
      volumes:
        - name: pgfarm-ssl
          secret:
            secretName: pgfarm-ssl
