apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  template:
    spec:
      containers:
        - name: client
          image: us-docker.pkg.dev/pgfarm-419213/containers/pgfarm-service:0.4.0
          env:
            - name: APP_URL
              value: https://pgfarm.library.ucdavis.edu
            - name: METRICS_ENABLED
              value: 'true'
            - name: METRICS_EXPORT_GC
              value: 'true'
