apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-fuse-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 500Gi
  storageClassName: gcs-storage-class
  claimRef:
    namespace: default
    name: gcs-fuse-pvc
  mountOptions:
    - implicit-dirs
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: app-database-backups