apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: admin-db
spec:
  selector:
    matchLabels:
      app: admin-db
  replicas: 1
  serviceName: admin-db
  template:
    metadata:
      labels:
        app: admin-db
        pgfarm-type: core-service
    spec:
      containers:
        - name: admin-db
          image: us-west1-docker.pkg.dev/digital-ucdavis-edu/pub/postgres:16
          args:
            - '-c'
            - max_connections=100
          imagePullPolicy: Always
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_HOST_AUTH_METHOD
              value: password
            - name: POSTGRES_PASSWORD
              value: postgres
          resources:
            limits:
              memory: 2Gi
              cpu: '2'
            requests:
              memory: 500Mi
              cpu: 200m
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: admin-db-ps
              mountPath: /var/lib/postgresql/data
            - name: pg-socket
              mountPath: /var/run/postgresql
        - name: pg-helper
          image: us-docker.pkg.dev/pgfarm-419213/containers/pgfarm-service:sandbox
          args:
            - npm
            - run
            - pg-helper
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: LOG_LEVEL
              value: info
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/google/service-account.json
            - name: SERVICE_NAME
              value: pg-helper
          volumeMounts:
            - name: pg-socket
              mountPath: /var/run/postgresql
            - name: service-account
              mountPath: /etc/google
      volumes:
        - name: pg-socket
          emptyDir: {}
        - name: service-account
          secret:
            secretName: service-account
      nodeSelector:
        intendedfor: services
  volumeClaimTemplates:
    - metadata:
        name: admin-db-ps
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
