apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
        pgfarm-type: gateway
    spec:
      containers:
      - name: gateway
        image: us-docker.pkg.dev/pgfarm-419213/containers/pgfarm-service:sandbox
        imagePullPolicy: Always
        command: ["/services/start", "gateway"]
        env:
        - name: SERVICE_NAME
          value: "gateway"
        envFrom:
        - secretRef:
            name: app-env
        - configMapRef:
            name: app-config
        resources:
          limits:
            memory: "2Gi"
            cpu: "2"
          requests:
            memory: "256Mi"
            cpu: "100m"
        volumeMounts:
          - mountPath: /etc/google
            name: service-account
      nodeSelector:
        intendedfor: services
      volumes:
      - name: service-account
        secret:
          secretName: service-account