apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  template:
    spec:
      containers:
      - name: client
        image: {{PG_FARM_SERVICE_IMAGE}}:{{BRANCH_TAG_NAME}}
        imagePullPolicy: Never
        env:
        - name : "APP_URL"
          value : "http://localhost:3000"
        - name: METRICS_ENABLED
          value: "false"
        - name: METRICS_EXPORT_GC
          value: "false"
        - name : "K8S_PLATFORM"
          value: "docker-desktop"
        - name : "CLIENT_ERROR_REPORTING_ENABLED"
          value : "true"
        - name : "CLIENT_ERROR_REPORTING_URL"
          value : "https://client-error-reporter-akwemh35fa-uw.a.run.app"
        - name : "CLIENT_ERROR_REPORTING_KEY"
          value : "6Ff+UkvNLivtnQ"
        volumeMounts:
        - name: src-client
          mountPath: /services/client
        - name: src-lib
          mountPath: /services/lib
        - name: src-models
          mountPath: /services/models
        - name: kubeconfig
          mountPath: /root/.kube
      volumes:
        - name: src-client
          hostPath:
            path: {{REPO_DIR}}/services/client
        - name: src-lib
          hostPath:
            path: {{REPO_DIR}}/services/lib
        - name: src-models
          hostPath:
            path: {{REPO_DIR}}/services/models
        - name: kubeconfig
          configMap:
            name: kubeconfig