apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
        pgfarm-type: core-service
    spec:
      containers:
      - name: admin
        imagePullPolicy: Always
        image: us-docker.pkg.dev/pgfarm-419213/containers/pgfarm-service:sandbox
        command: ["/services/start", "administration"]
        env:
        - name: LOG_LEVEL
          value: "info"
        - name : "GOOGLE_APPLICATION_CREDENTIALS"
          value : "/etc/google/service-account.json"
        envFrom:
        - secretRef:
            name: app-env
        resources:
          limits:
            memory: "2Gi"
            cpu: "2"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
          - mountPath: /etc/google
            name: service-account
      volumes:
      - name: service-account
        secret:
          secretName: service-account
      nodeSelector:
        intendedfor: services