apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - path: statefulset.yaml
    target:
      kind: StatefulSet
  - target:
      kind: Service
    patch: |-
      - op: remove
        path: /spec/clusterIP
        target:
          kind: Service
  - path: service.yaml
    target:
      kind: Service