apiVersion: v1
kind: Service
metadata:
  name: admin-db
spec:
  type: NodePort
  selector:
    app: admin-db
  ports:
  - name: postgres
    protocol: TCP
    nodePort: 30544
    port: 5432
    targetPort: 5432