apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-dev
spec:
  template:
    spec:
      containers:
      - name: gateway
        image: us-docker.pkg.dev/pgfarm-419213/containers/pgfarm-service:main
        command: ["bash", "-c", "tail -f /dev/null"]
        env:
        - name : "APP_URL"
          value : "http://dev-gateway.pgfarm.library.ucdavis.edu"
        - name : "GATEWAY_HTTP_ENABLED"
          value : "true"
        - name: METRICS_ENABLED
          value: "true"
        - name: METRICS_EXPORT_GC
          value: "true"
        # - name: PROXY_TLS_CERT
        #   value: "/etc/pgfarm/certs/pgfarm.library.ucdavis.edu/ssl-pgfarm.crt"
        # - name: PROXY_TLS_KEY
        #   value: "/etc/pgfarm/certs/pgfarm.library.ucdavis.edu/ssl-pgfarm.key"
        # - name: PROXY_TLS_ENABLED
        #   value: "true"
      #   volumeMounts:
      #     - mountPath: /etc/pgfarm/certs/pgfarm.library.ucdavis.edu
      #       name: pgfarm-ssl
      # volumes:
      # - name: pgfarm-ssl
      #   secret:
      #     secretName: pgfarm-ssl