apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  template:
    spec:
      containers:
      - name: gateway
        image: {{PG_FARM_SERVICE_IMAGE}}:{{BRANCH_TAG_NAME}}
        imagePullPolicy: Never
        env:
        - name: PROXY_DEBUG
          value: "false"
        - name: LOG_LEVEL
          value: "debug"
        - name : "APP_URL"
          value : "http://localhost:3000"
        - name : "GATEWAY_HTTP_ENABLED"
          value : "true"
        - name: METRICS_ENABLED
          value: "false"
        - name: METRICS_EXPORT_GC
          value: "false"
        - name : "K8S_PLATFORM"
          value: "docker-desktop"
        volumeMounts:
        - name: src-gateway
          mountPath: /services/gateway
        - name: src-administration
          mountPath: /services/administration
        - name: src-lib
          mountPath: /services/lib
        - name: src-models
          mountPath: /services/models
        - name: kubeconfig
          mountPath: /root/.kube
      volumes:
        - name: src-gateway
          hostPath:
            path: {{REPO_DIR}}/services/gateway
        - name: src-administration
          hostPath:
            path: {{REPO_DIR}}/services/administration
        - name: src-lib
          hostPath:
            path: {{REPO_DIR}}/services/lib
        - name: src-models
          hostPath:
            path: {{REPO_DIR}}/services/models
        - name: kubeconfig
          configMap:
            name: kubeconfig