apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  template:
    spec:
      containers:
        - name: client
          image: us-docker.pkg.dev/pgfarm-419213/containers/pgfarm-service:local-dev
          env:
            - name: CLIENT_STATIC_ASSETS_BASE_URL
              value: "http://localhost:30000/static-assets"
