apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  template:
    spec:
      containers:
      - name: client
        env:
        - name : "APP_URL"
          value : "http://localhost:3000"
        - name: METRICS_ENABLED
          value: "false"
        - name: METRICS_EXPORT_GC
          value: "false"
        - name : "K8S_PLATFORM"
          value: "docker-desktop"
        - name : "PG_INSTANCE_IMAGE"
          value : "localhost/local-dev/postgres:16"
        - name: SWAGGER_UI_TESTING_DOMAIN
          value: "http://pgfarm.local:30000"