apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcs-fuse-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: gcs-fuse-pv
  storageClassName: gcs-storage-class