apiVersion: v1
kind: Service
metadata:
  annotations:
    # Use external passthrough load balancer
    # https://cloud.google.com/kubernetes-engine/docs/how-to/external-svc-lb-rbs
    # https://cloud.google.com/load-balancing/docs/passthrough-network-load-balancer
    cloud.google.com/l4-rbs: "enabled"
spec:
  loadBalancerIP: "{{GKE_EXTERNAL_IP}}"
  # Use local traffic policy to preserve client source IP
  externalTrafficPolicy: Local

