apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  template:
    spec:
      containers:
      - name: admin
        env:
        - name : "APP_URL"
          value : "http://localhost:3000"
        - name : "K8S_PLATFORM"
          value: "docker-desktop"
        volumeMounts:
        - name: kubeconfig
          mountPath: /root/.kube
      volumes:
        - name: kubeconfig
          configMap:
            name: kubeconfig