apiVersion: v1
kind: Service
metadata:
  name: gateway-dev-ingress
spec:
  type: LoadBalancer
  selector:
    app: gateway-dev
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https 
    protocol: TCP
    port: 443
    targetPort: 443