apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: us-docker.pkg.dev/pgfarm-419213/containers/pgfarm-service:sandbox
        imagePullPolicy: Always
        command: ["/services/start", "client"]
        env:
        - name: LOG_LEVEL
          value: "info"
        - name : "GOOGLE_APPLICATION_CREDENTIALS"
          value : "/etc/google/service-account.json"
        - name: SERVICE_NAME
          value: "client"
        - name : "CLIENT_ERROR_REPORTING_ENABLED"
          value : "true"
        - name : "CLIENT_ERROR_REPORTING_URL"
          value : "https://client-error-reporter-akwemh35fa-uw.a.run.app"
        - name : "CLIENT_ERROR_REPORTING_KEY"
          value : "6Ff+UkvNLivtnQ"
        envFrom:
        - secretRef:
            name: app-env
        resources:
          limits:
            memory: "2Gi"
            cpu: "2"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
          - mountPath: /etc/google
            name: service-account
      nodeSelector:
        intendedfor: services
      volumes:
      - name: service-account
        secret:
          secretName: service-account